CREATE TABLE IF NOT EXISTS users (
    created_at TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    name VARCHAR (255) NOT NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (100) NOT NULL
)