// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/MochamadAkbar/go-restful/config"
	"github.com/MochamadAkbar/go-restful/handler"
	"github.com/MochamadAkbar/go-restful/repository"
	"github.com/MochamadAkbar/go-restful/usecase"
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
)

// Injectors from dependency.go:

func InitializeServer(conn *pgxpool.Pool) *http.Server {
	iUserRepository := repository.NewUserRepository(conn)
	iUserUsecase := usecase.NewUserUsecase(iUserRepository)
	mux := config.NewRouter()
	httpHandler := handler.NewUserHandler(iUserUsecase, mux)
	server := config.NewServer(httpHandler)
	return server
}
