// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/MochamadAkbar/go-restful/handler"
	"github.com/MochamadAkbar/go-restful/repository"
	"github.com/MochamadAkbar/go-restful/usecase"
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from dependency.go:

func InitializeUserService(conn *pgxpool.Pool, router chi.Router) error {
	iUserRepository := repository.NewUserRepository(conn)
	iUserUsecase := usecase.NewUserUsecase(iUserRepository)
	error2 := handler.NewUserHandler(iUserUsecase, router)
	return error2
}
